### ISSUE TITLE
[QUESTION] Will this work for a browser <-> server p2p connection?

### ISSUE THREAD

**Issue by OmarB97** [NickCis/simple-peerjs#7]
Hi, just found this package that looks like it may be the solution I'm looking for, which is a browser <-> server p2p WebRTC connection (rather than between browsers)

I'm just trying to send the browser's mediaStream (audio + video stream) over to the server to do additional work with it and eventually send it to an RTMP endpoint. Will this fit my needs? Thanks!

**Comment by NickCis** [comment]
Hi Omar,
It should work browser to server p2p connection, under the hood this library is using [simple-peer](https://github.com/feross/simple-peer), so you should check their documentation on how to do it. I did a quick check and the examples only provide browser to browser video streamming, I'm not sure how you should get the `avigator.mediaDevices.getUserMedia`'s stream on node.

Just to be clear this library, `simple-peerjs`, is just a wrapper of `simple-peer` in order to make signaling exchange using the [`peerjs` protocol](https://peerjs.com/).

**Comment by OmarB97** [comment]
Sounds good, will try it thanks!
